### ISSUE TITLE
Automatic Installation of Python Dependencies

### ISSUE THREAD

**Issue by cortner** [libAtoms/ASE.jl#1]
seems to fail at the moment. See discussion in [JuLIP.jl](https://github.com/libAtoms/JuLIP.jl/issues/75)

**Comment by lifelemons** [comment]
Hey, 

In the file [build.jl](https://github.com/libAtoms/ASE.jl/blob/master/deps/build.jl) changing [this line](https://github.com/libAtoms/ASE.jl/blob/0f3ba8f9673bbc5b6bc391067656c04029e98355/deps/build.jl#L20) to ``` pipcmd = `$(PyCall.python) -m pip install --upgrade --user $(pkgname)` ```, I think, solves the build issues. It invokes pip via the python being used by PyCall

Ive tested it by calling (since I'm not sure how to `Pkg.add` a local repo/package) - you may need to test that)
```
[in terminal] julia .../ASE.jl/deps/build.jl
[in julia] 
include(".../ASE.jl/src/ASE.jl")
```
seems to get included without errors and running some tests seems fine.

**Comment by cortner** [comment]
Thank you for playing around with the! I'm happy for you to make a PR, if you are willing?

**Comment by lifelemons** [comment]
I didn't have acess to push a new branch. (I thought creating a whole forked repository seemed a bit excessive, as I'd delete it straight after) Though which would you prefer?

**Comment by cortner** [comment]
Normally I'd just give you access but I don't want to mess around with permissions in `libatoms` so would prefer a PR if that's ok. I don't think creating a fork does much actual work. You can do everything from Julia: 
```Julia
Pkg.checkout("Images")           # check out the master branch
<here, make sure your bug is still a bug and hasn't been fixed already>
cd(Pkg.dir("Images"))
;git checkout -b myfixes         # create a branch for your changes
<edit code>                      # be sure to add a test for your bug
Pkg.test("Images")               # make sure everything works now
;git commit -a -m "Fix foo by calling bar"   # write a descriptive message
using PkgDev
PkgDev.submit("Images")
```

**Comment by lifelemons** [comment]
Sure, I'll do it via a forked repo

**Comment by cortner** [comment]
this seems to be working well for now
